// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJjXWP_mZF094_Zv3Um1B6OlzdoYq_8jw',
    appId: '1:644303970101:web:51246abecc5885420af67c',
    messagingSenderId: '644303970101',
    projectId: 'agrilease-ecd0b',
    authDomain: 'agrilease-ecd0b.firebaseapp.com',
    storageBucket: 'agrilease-ecd0b.appspot.com',
    measurementId: 'G-6GZQRXEFL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa6jmt826rK1vlfnHYZkn9_xuPZpv6NfM',
    appId: '1:644303970101:android:e84a00264fc732540af67c',
    messagingSenderId: '644303970101',
    projectId: 'agrilease-ecd0b',
    storageBucket: 'agrilease-ecd0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNC1g-6zxLYBi_FM01jf3m_LvJATFG5c',
    appId: '1:644303970101:ios:305c3813f8e449ea0af67c',
    messagingSenderId: '644303970101',
    projectId: 'agrilease-ecd0b',
    storageBucket: 'agrilease-ecd0b.appspot.com',
    iosBundleId: 'com.example.agrilease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNC1g-6zxLYBi_FM01jf3m_LvJATFG5c',
    appId: '1:644303970101:ios:8062093a21ba307f0af67c',
    messagingSenderId: '644303970101',
    projectId: 'agrilease-ecd0b',
    storageBucket: 'agrilease-ecd0b.appspot.com',
    iosBundleId: 'com.example.agrilease.RunnerTests',
  );
}
